mysql-backup:
  container_name: mysql-backup
  build: .
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
    CRON_TIME: "* * * * *"
    BACKUP_MAX: 3
    BACKUP_DB: --all-databases
    BACKUP_OPTS:
